---
- name: Nginx | Install
  hosts: all
  remote_user: root
  tasks:
    - apt: pkg=nginx state=latest
      register: installed
      notify:
        - NGINX start

  handlers:
    - name: NGINX start
      service: name=nginx state=started
